title = "LibNetwork Configuration file"

[daemon]
  debug = true
  labels = ["com.docker.network.driver.overlay.hostmode=true"]
[cluster]
  discovery = "etcd://localhost:2379"
[datastore]
  embedded = false
[datastore.client]
  provider = "etcd"
  Address = "localhost:2379"
[scopes]
  [scopes.global]
      [scopes.global.client]
            provider = "etcd"
                  address = "localhost:2379"
